# Generated by Django 5.2.9 on 2025-12-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BTC', 'Bitcoin'), ('USDT', 'Tether USDT'), ('TRX', 'TRON')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('rate_to_irt', models.DecimalField(decimal_places=2, help_text='نرخ تبدیل ۱ واحد این ارز به تومان (IRT)', max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['code'],
            },
        ),
    ]
