# Generated by Django 5.2.4 on 2025-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tehran_cgf', 'Currencies Source'), ('nobitex_spot', 'Cryptocurrencies Source')], max_length=32)),
                ('market', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('source', 'market')},
            },
        ),
    ]
