# Generated by Django 5.2.4 on 2025-07-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='code',
            field=models.CharField(default='a', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketprice',
            name='name',
            field=models.CharField(default='a', max_length=16),
            preserve_default=False,
        ),
    ]
