# Generated by Django 5.2.9 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_to_irt',
            field=models.DecimalField(decimal_places=2, help_text='Exchange rate to Iranian Rial (IRT)', max_digits=24),
        ),
    ]
