# Generated by Django 5.2.4 on 2025-07-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_marketprice_code_marketprice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketprice',
            old_name='price',
            new_name='rate',
        ),
    ]
