# Generated by Django 5.2.4 on 2025-07-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_rename_price_marketprice_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='icon',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
