# Generated by Django 5.2.4 on 2025-07-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_marketprice_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='icon',
            field=models.CharField(max_length=32),
        ),
    ]
