# Generated by Django 5.2.9 on 2025-12-31 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('message_fa', models.TextField()),
                ('message_en', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('order', 'Order Update'), ('charge', 'Charge Success'), ('ticket', 'Ticket Reply'), ('system', 'System')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='e.g. /tickets/123 or /orders/456', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
