# Generated by Django 5.2.9 on 2025-12-31 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی (فارسی)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Category Name (EN)')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='Title (FA)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('description_fa', models.TextField(verbose_name='Description (FA)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(max_length=200, verbose_name='icon')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='services/banners/')),
                ('commission_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission (%)')),
                ('commission_fixed', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Fixed Commission (Toman))')),
                ('min_amount', models.DecimalField(decimal_places=0, default=10000, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Minimum Payable Amount (Toman)')),
                ('max_amount', models.DecimalField(decimal_places=0, default=100000000, max_digits=15, verbose_name='Maximum Payable Amount (Toman)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('user_pricing', models.BooleanField(default=True, verbose_name='Allow user to set the amount')),
                ('delivery_time_fa', models.CharField(blank=True, max_length=100)),
                ('delivery_time_en', models.CharField(blank=True, max_length=100)),
                ('requires_manual_review', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='Required Fields Configuration')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title_fa'],
            },
        ),
    ]
