# Generated by Django 5.2.8 on 2025-11-30 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fa",
                    models.CharField(
                        max_length=100, verbose_name="نام دسته\u200cبندی (فارسی)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Category Name (EN)"),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "دسته\u200cبندی خدمات",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=200, verbose_name="عنوان سرویس (فارسی)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (EN)"
                    ),
                ),
                ("description_fa", models.TextField(verbose_name="توضیحات (فارسی)")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (EN)"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="services/icons/", verbose_name="آیکون"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/banners/"
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مقداری ثابت")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="کارمزد (%)",
                    ),
                ),
                (
                    "commission_fixed",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="اگر نوع کارمزد 'مقداری ثابت' باشد",
                        max_digits=12,
                        verbose_name="کارمزد ثابت (تومان)",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=10000,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1000)],
                        verbose_name="حداقل مبلغ قابل پرداخت (تومان)",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=100000000,
                        max_digits=15,
                        verbose_name="حداکثر مبلغ قابل پرداخت (تومان)",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.0,
                        max_digits=5,
                        verbose_name="مالیات (%)",
                    ),
                ),
                (
                    "delivery_time_fa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="زمان تحویل (فارسی)"
                    ),
                ),
                ("delivery_time_en", models.CharField(blank=True, max_length=100)),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=True, verbose_name="نیاز به بررسی دستی؟"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرویس",
                "verbose_name_plural": "سرویس\u200cها",
                "ordering": ["category__order", "order", "title_fa"],
            },
        ),
    ]
