# Generated by Django 5.2.8 on 2025-12-02 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["category__order", "order", "title_fa"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="services.category",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="commission_fixed",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Fixed Commission (Toman))",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Commission (%)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="delivery_time_fa",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="description_fa",
            field=models.TextField(verbose_name="Description (FA)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(upload_to="services/icons/", verbose_name="icon"),
        ),
        migrations.AlterField(
            model_name="service",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=100000000,
                max_digits=15,
                verbose_name="Maximum Payable Amount (Toman)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=10000,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1000)],
                verbose_name="Minimum Payable Amount (Toman)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="requires_manual_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=9.0, max_digits=5, verbose_name="Tax Rate (%)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title_fa",
            field=models.CharField(max_length=200, verbose_name="Title (FA)"),
        ),
    ]
