# Generated by Django 5.2.2 on 2025-07-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
