# Generated by Django 5.2.8 on 2025-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_options_alter_service_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order", "title_fa"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(max_length=200, verbose_name="icon"),
        ),
    ]
