# Generated by Django 5.2.9 on 2025-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Required Fields Configuration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='commission_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10),
        ),
    ]
