# Generated by Django 5.2.9 on 2025-12-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_required_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user_pricing',
            field=models.BooleanField(default=True, verbose_name='Allow user to set the amount'),
        ),
    ]
