# Generated by Django 5.2.9 on 2025-12-28 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(default=datetime.time(9, 0), help_text='Start time for availability (HH:MM)')),
                ('time_to', models.TimeField(default=datetime.time(17, 0), help_text='End time for availability (HH:MM)')),
                ('weekday_from', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Start weekday (0=Monday to 6=Sunday)')),
                ('weekday_to', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=4, help_text='End weekday (0=Monday to 6=Sunday)')),
                ('global_availability', models.BooleanField(default=True, help_text='Overall service availability toggle')),
                ('enable_schedule', models.BooleanField(default=False, help_text='Enable schedule if True')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ensure_singleton')],
            },
        ),
    ]
