# Generated by Django 5.2.9 on 2025-12-28 08:15

import datetime
from django.db import migrations, models


def create_initial_settings(apps, schema_editor):
    GlobalSettings = apps.get_model('core', 'GlobalSettings')
    if not GlobalSettings.objects.exists():
        GlobalSettings.objects.create(
            id=1,
            time_from='09:00:00',
            time_to='17:00:00',
            weekday_from=0,
            weekday_to=4,
            global_availability=True,
            enable_schedule=False,
        )


def remove_settings(apps, schema_editor):
    GlobalSettings = apps.get_model('core', 'GlobalSettings')
    GlobalSettings.objects.filter(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_settings, reverse_code=remove_settings),
    ]
