# Generated by Django 5.2.9 on 2026-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalsettings_initial_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='erfapay_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='erfapay_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='erfapay_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='erfapay_phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='erfapay_social',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
