# Generated by Django 5.2.9 on 2025-12-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_amount_irt', models.DecimalField(decimal_places=0, help_text='Amount user entered', max_digits=20)),
                ('commission_irt', models.DecimalField(decimal_places=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_irt', models.DecimalField(decimal_places=0, help_text='Final amount deducted', max_digits=20)),
                ('usd_irt_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custom_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='orders/attachments/')),
            ],
        ),
    ]
