# Generated by Django 5.2.9 on 2026-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_attachment',
            field=models.FileField(blank=True, help_text='Internal admin attachment', upload_to=''),
        ),
    ]
