# Generated by Django 5.2.9 on 2025-12-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_amount', models.DecimalField(decimal_places=2, help_text='Amount in foreign currency (e.g., USD)', max_digits=10)),
                ('irt_amount', models.DecimalField(decimal_places=0, help_text='Converted amount in IRT', max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='USD to IRT rate at charge time', max_digits=10)),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('crypto', 'Crypto'), ('voucher', 'Voucher')], max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('admin_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, help_text='Balance in Iranian Toman (IRT)', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Positive for charge/adjustment add, negative for spend/adjustment subtract', max_digits=20)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('spend', 'Spend'), ('adjustment', 'Adjustment')], max_length=20)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('admin_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
