# Generated by Django 5.2.9 on 2025-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی (فارسی)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Category Name (EN)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تیکت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت',
                'ordering': ['order', 'title_fa'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory'),
        ),
    ]
