# Generated by Django 5.2.9 on 2025-12-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='attachment',
        ),
        migrations.CreateModel(
            name='TicketMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/attachments/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tickets.ticketmessage')),
            ],
        ),
    ]
