# Generated by Django 5.2.9 on 2025-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticketmessage_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessageattachment',
            old_name='file',
            new_name='attachment',
        ),
    ]
